package instruction

const (
	REGISTER_SYMBOL_A   string = "a"
	REGISTER_SYMBOL_B   string = "b"
	REGISTER_SYMBOL_C   string = "c"
	REGISTER_SYMBOL_D   string = "d"
	REGISTER_SYMBOL_SP  string = "sp"
	REGISTER_SYMBOL_IPL string = "ipl"
	REGISTER_SYMBOL_IPH string = "iph"
)

const (
	REGISTER_OPCODE_A   uint8 = 0b000
	REGISTER_OPCODE_B   uint8 = 0b001
	REGISTER_OPCODE_C   uint8 = 0b010
	REGISTER_OPCODE_D   uint8 = 0b011
	REGISTER_OPCODE_IPL uint8 = 0b100
	REGISTER_OPCODE_IPH uint8 = 0b101
	REGISTER_OPCODE_SP  uint8 = 0b111
)

var (
	REGISTER_SYMBOL_TO_OPCODE = map[string]uint8{
		REGISTER_SYMBOL_A:   REGISTER_OPCODE_A,
		REGISTER_SYMBOL_B:   REGISTER_OPCODE_B,
		REGISTER_SYMBOL_C:   REGISTER_OPCODE_C,
		REGISTER_SYMBOL_D:   REGISTER_OPCODE_D,
		REGISTER_SYMBOL_IPL: REGISTER_OPCODE_IPL,
		REGISTER_SYMBOL_IPH: REGISTER_OPCODE_IPH,
		REGISTER_SYMBOL_SP:  REGISTER_OPCODE_SP,
	}
)
